#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>

#define MAXLINE 4096 /*max text line length*/
#define SERV_PORT 3000 /*port*/

#ifndef O_ASYNC
#define O_ASYNC FASYNC
#endif

int sockfd;

void signio_handler(int signo)
{
  char buff[1024];
  int n = recv(sockfd, buff, sizeof(buff), 0);
  //if (n>0) // if SIGIO is generated by a data arrival
    printf("Received from server (%d bytes), content: %s\n",n, buff);
  memset(buff,0,sizeof(buff));
}

int main(int argc, char **argv) 
{
	
 //int sockfd;
 struct sockaddr_in servaddr;
 char sendline[MAXLINE], recvline[MAXLINE];
	
 //basic check of the arguments
 //additional checks can be inserted
 if (argc !=2) {
  perror("Usage: TCPClient <IP address of the server"); 
  exit(1);
 }
	
 //Create a socket for the client
 //If sockfd<0 there was an error in the creation of the socket
 if ((sockfd = socket (AF_INET, SOCK_STREAM, 0)) <0) {
  perror("Problem in creating the socket");
  exit(2);
 }
	
 //Creation of the socket
 memset(&servaddr, 0, sizeof(servaddr));
 servaddr.sin_family = AF_INET;
 servaddr.sin_addr.s_addr= inet_addr(argv[1]);
 servaddr.sin_port =  htons(SERV_PORT); //convert to big-endian order
	
 //Connection of the client to the socket 
 if (connect(sockfd, (struct sockaddr *) &servaddr, sizeof(servaddr))<0) {
  perror("Problem in connecting to the server");
  exit(3);
 }
 
  // Signal driven I/O mode and NONBlOCK mode so that recv will not block 
  if(fcntl(sockfd, F_SETFL, O_NONBLOCK | O_ASYNC))
      printf("Error in setting socket to async, nonblock mode");  
  
  signal(SIGIO, signio_handler); // assign SIGIO to the handler

  //set this process to be the process owner for SIGIO signal 
  if (fcntl(sockfd, F_SETOWN, getpid()) <0)
      printf("Error in setting own to socket");

  char str[50];
  while (1) {
    printf("Client: ");
    gets(str);  
    send(sockfd, str, sizeof(str),0);
    memset(str,0,sizeof(str));
  }
  
  exit(0);
}
